# Hugo variables
#
baseurl = "https://xj.io/"
languageCode = "en-us"
title = "XJ Music®"
# number of posts to show on home/category/tag pages (Default: 10)
paginate = 25
# optionally override the site's footer with custom copyright text
copyright = "XJ Music Inc."
#disqusShortname = "XYW"
theme = "xj-theme"

[taxonomies]
  category = "categories"
  page = "pages"
  resource = "resources"
  tag = "tags"

[permalinks]
  resources = "/resources/:year/:slug/"
  page = "/:slug/"

#[[menu.sidebar]]
#  name = "Link 1"
#  url = "https://example.com"
#
#[[menu.sidebar]]
#  name = "Link 2"
#  url = "https://example.org"

# custom navbar menu entry.   See the custom_navbar parameter below for
# details.

#[[menu.navbar]]
#  name = "Link 1"
#  url = "https://example.org"

# Theme variables
#
[params]
  # Text
  author = "XJ Music®"
  email = "hello@xj.io"
  images = ["https://xj.io/images/cover.jpg"]
  description = "The XJ Music® platform is an entirely new AI powered medium, transforming the experience of music in shared spaces."

  # Analytics
  googleAnalytics = "UA-102762643-3"

  # With so many things competing for their attention, your visitors and customers hate to be overwhelmed by the wrong music.
  # Research shows that the perfect music will please visitors, and arouse customers.
  # XJ™ delivers top-class, 24/7 non-stop custom never-before-heard music, with a guaranteed aesthetic⸺ all using your existing equipment, for 60% less than other commercial music options.

  # Format dates with Go's time formatting
  date_format = "Mon Jan 02, 2006"

  # verification string for Google Webmaster Tools
  #google_verify_meta = "BAi57DROASu4b2mkVNA_EyUsobfA7Mq8BmSg7Rn-Zp9"

  # verification string for Bing Webmaster Tools
  #bing_verify_meta = "3DA353059F945D1AA256B1CD8A3DA847"

  # verification string for Yandex Webmaster Tools
  #yandex_verify_meta = "66b077430f35f04a"

  # Optionally display a message about the site's use of cookies, which may be
  # required for your site in the European Union. Set the parameter below to a
  # page where the user can get more information about cookies, either on your
  # site or externally, for example:
  #cookie_consent_info_url = "/cookie-information/"
  #cookie_consent_info_url = "http://cookiesandyou.com"

  # customise the contents of the navbar at the top of the page.  The default
  # behaviour is to list all static pages not in the posts directory. When the
  # parameter below is set to true you will have to manually add entries to the
  # navbar, either by adding the following menu variable to the front matter of
  # the relevant pages
  #   menu = "navbar"
  # or by specifying menu entries in a similar way to the sidebar menu above.
  #custom_navbar = true

  # show sharing icons on pages/posts (default: true)
  #sharingicons = true

  # Display post summaries instead of content in list templates (default: true)
  truncate = true

  # Disable the use of sub-resource integrity on CSS/JS assets (default: false)
  # Useful if you're using a CDN or other host where you can't control cache headers
  #disable_sri = false

  [params.sidebar]
    # Optional about block for sidebar (can be Markdown)
    about = "Exclusive licensee of the <a href='https://xj.outright.io' target='_blank' aria-description='XJ Music® '>XJ Music®</a> for institutional, industrial and commercial purposes."

    # How many posts to show on the sidebar (Default: 5)
    #num_recent_posts = 2

  [params.social]
    # Optional, used for attribution in Twitter cards (patternlly not a person
    # for example: nytimes, flickr, NatGeo, etc).
    # See: https://dev.twitter.com/cards/types/summary-large-image
    facebook = "xjmusicstream"
    twitter = "xj_music"

# Default content language for Hugo 0.17's multilingual support (default is "en")
# See: https://github.com/spf13/hugo/blob/master/docs/content/content/multilingual.md
#DefaultContentLanguage = "en"

# Languages to render
#[languages.en]
#[languages.bg]

# vim: ts=2 sw=2 et
